version: '3'
services:
    api: #api principal
        build: ./api
        #environment:
        #    DATABASE_HOST: db
        #    MYSQL_PORT: 3306
        #    MYSQL_DATABASE: senz
        #    MYSQL_USER: mysql
        #    MYSQL_PASSWORD: Adsum123
        #    TZ: "America/Mazatlan"
        ports:
            - "3000:3000"
        networks:
            - hidro-net
        restart: on-failure    
    front: #front
        build: ./front
        environment:
            TZ: "America/Mazatlan"
        ports:
            - "80:80"
        networks:
            - hidro-net
        restart: on-failure
networks:
    hidro-net:
        driver: bridge